services:
  next:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./missing-persons/:/code
    user: "1000:998"
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: testing
  
