version: '3.9'

services:

  next:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - ./missing-persons/:/code
    command: npx next dev
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testing
  
