services:
  playwright:
    build:
      context: .
      dockerfile: Dockerfile.test
      target: build
    ports:
      - "9323:9323"
      - "3000:3000"
    command: /bin/bash -c "npm run start & sleep 3 && npx playwright test"
