services:
  next:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"  
    volumes:
      - ./:/code
    user: "1000:998"

  db: 
    image: mysql
    restart: always
    ports:
      - "3001:3306" 
    environment:
      MYSQL_HOST: missing-persons-db.cngqqsemssns.us-east-2.rds.amazonaws.com
      MYSQL_DATABASE: missing-persons-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: missingdb
